apiVersion: apps/v1
kind: Deployment 
metadata:
  name: audit
  namespace: seblak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit
  template:
    metadata:
      labels:
        app: audit
    spec:
      containers:
      - name: audit
        image: audit:local
        imagePullPolicy: IfNotPresent
        env:
        - name: NATS_URL
          value: "nats://nats:4222"
        - name: DB_PATH
          value: "/data/audit.db"
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: audit-data
